name: ghpages

on: 
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - name: Push to GH pages
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git remote set-url origin https://bladedancer:${ACCESS_TOKEN}@github.com/bladedancer/fed-viz.git 
          git push origin `git subtree split --prefix client/dist master`:gh-pages --force
