name: ghpages

on: 
  push:
    # only trigger on branches, not on tags
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          git subtree push --prefix client/dist origin gh-pages
